logging:
  level:
    com.github.devgcoder: DEBUG
  pattern:
    file: '%date{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    console: '%date{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
  file:
    max-history: 7
    name: ./logs/demo.log

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mybatis-entity?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver